services:
  db:
    build: .
    container_name: sqlserver
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: MyPassword.123
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: